# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19vyMbrEPGjJ6oVuyVctipTx1QkAO0qX_
"""

from google.colab import drive
drive.mount('/content/drive')

import os

# Define the correct data directory path
data_dir = r"/content/drive/MyDrive/dataset/lung-and-colon-cancer-histopathological-images"

# Check if the directory exists, if not, create it
if not os.path.exists(data_dir):
    os.makedirs(data_dir)  # Create the directory
    print(f"Created missing directory: {data_dir}")
else:
    print(f"Directory exists: {data_dir}")

# Debugging: Print the absolute path to check correctness
print("Looking for data in:", os.path.abspath(data_dir))

# Now list the files safely
try:
    folds = os.listdir(data_dir)
    print("Files in directory:", folds)
except FileNotFoundError:
    print(f"Error: Directory '{data_dir}' does not exist. Please check the path.")
except PermissionError:
    print(f"Error: Permission denied for accessing '{data_dir}'. Try running as Administrator.")

# prompt: i have to add this above directory to git hub repo

import os

# Define the correct data directory path *within your repository*
data_dir = "/content/drive/MyDrive/dataset/lung-and-colon-cancer-histopathological-images" # Change to the correct relative path

# Check if the directory exists
if not os.path.exists(data_dir):
    print(f"Error: Directory '{data_dir}' does not exist. Please download the dataset to this location.")
else:
    print(f"Directory exists: {data_dir}")

# Now list the files safely
try:
    folds = os.listdir(data_dir)
    print("Files in directory:", folds)
except FileNotFoundError:
    print(f"Error: Directory '{data_dir}' does not exist. Please check the path.")
except PermissionError:
    print(f"Error: Permission denied for accessing '{data_dir}'.")

